[#rnfb60-bug]
= Bugs Fixed

////
Individual issue template:

_https://github.com/FirebirdSQL/firebird/issues/nnnn[#nnnn]_
-- A description

_Fixed by Some Person_

'''

<end of issue template>

General outline (<version> ::= <major><minor><patch>[<pre>]):

[#bug-<version>]
== Firebird <major>.<minor>.<patch>[-<pre>] Release: Bug Fixes

[#bug-<version>-core]
=== Core Engine

[#bug-<version>-crashes]
=== Server Crashes/Hang-ups

[#bug-<version>-api]
=== API/Remote Interface

[#bug-<version>-install]
=== Installation Issues

[#bug-<version>-utils]
=== Utilities

[#bug-<version>-util-isql]
==== isql

[#bug-<version>-util-gbak]
==== gbak

[#bug-<version>-util-<tool>]
==== <tool>

[#bug-<version>-<abbreviated-subject>]
=== <subject>

////

[#bug-600a1]
== Firebird 6.0.0 Alpha 1 Release: Bug Fixes

[#bug-600a1-core]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7476[#7476]_
-- Improvement on procedures/triggers to recognise changes in a domain used in `COALESCE`

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7600[#7600]_
-- `CASE` statement different result compared to Firebird 2.5.9

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7715[#7715]_
-- Support multibyte (UTF8) start/end character in alternative string literal

_Fixed by Adriano dos Santos Fernandes_

''''

[#bug-600a1-util-isql]
==== isql

_https://github.com/FirebirdSQL/firebird/pull/187_[#187]
-- If stdin is `FILE_TYPE_PIPE` treat it as non-interactive

_Fixed by Artyom Smirnov_

''''