[#rnfb60-fbconf]
= Configuration Additions and Changes

New configuration parameters:

// TODO Specific sections needed

[#rnfb60-config-other]
== Other Parameters

// TODO Remove section if no additions

[#rnfb60-config-changes]
== Changed configuration parameters

// TODO Remove section if no additions

[#rnfb60-replconf]
== Replication Configuration Additions and Changes

// TODO Remove section if no additions

[#rnfb60-config-cleanup]
== Removed configuration parameters

`MaxIdentifierByteLength`::
Previously used for restricting maximum identifier length in bytes.
The maximum is now always 252 bytes.

`MaxIdentifierCharLength`::
Previously used for restricting maximum identifier length in characters.
The maximum is now always 63 characters.

`RelaxedAliasChecking`::
Previously used to enable old Firebird 1.x relaxed alias rules to allow use of the table name in a column reference even if the table was aliased.
The strict alias rules are now always applied.

// TODO Other sections needed
