[#rnfb60-psql]
= Procedural SQL (PSQL)

[#rnfb60-psql-links]
.Quick Links
* <<rnfb60-psql-decl-var-init>>

[#rnfb60-psql-decl-var-init]
== `DECLARE VARIABLE` Initialiser Enhancements
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7590[#7590]

Any value expression can now be used to initialise a PSQL variable in `DECLARE VARIABLE`.
In previous Firebird versions, only a subset of expressions could be used (the same expressions as allowed in a column's or domain's `DEFAULT` clause).

.Syntax
[listing,subs=+quotes]
----
DECLARE [VARIABLE] _varname_ <type> [{ = | DEFAULT } <value-expression>];
----

[discrete]
=== Notes

Previously declared variables can be used in the initialiser expression of following variables.

A variable initialiser may call subroutines, and these subroutines may read and write previously declared variables.

A subroutine used in an initialiser may also write to variables declared after the one being initialised.
Their values will be overwritten when their initialisers are executed, even if they don't have explicit initialisers.

[source]
----
-- This block will return (<null>, 2) as values of v1 and v2 assigned in sf1 will
-- be overwritten by their initializer after sf1 is called.
execute block returns (o1 integer, o2 integer)
as
    declare function sf1 returns integer;

    declare v0 integer = sf1();
    declare v1 integer;
    declare v2 integer = 2;

    declare function sf1 returns integer
    as
    begin
        v1 = 10;
        v2 = 20;
        return 0;
    end
begin
    o1 = v1;
    o2 = v2;
    suspend;
end
----

It's an error if a subroutine reads a variable declared after the one being initialised like in the following example.

[source]
----
-- When sf1 is called, v1 is not yet initialized.
execute block
as
    declare function sf1 returns integer;

    declare v0 integer = sf1();
    declare v1 integer;

    declare function sf1 returns integer
    as
    begin
        return v1;
    end
begin
end
----
